[package]
name = "regular_expressions"
version = "0.1.0"
authors = ["claizelcoubeili <clcepe@up.edu.ph>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.1"

